# Generated by Django 3.0.1 on 2019-12-22 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='U_tracking_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori', models.CharField(max_length=3)),
                ('des', models.CharField(max_length=3)),
                ('eta', models.CharField(max_length=100, null=True)),
                ('etd', models.CharField(max_length=100, null=True)),
                ('flight_no', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Awb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_no', models.CharField(max_length=13)),
                ('awbs_list', models.ManyToManyField(to='api_manager_app.U_tracking_return')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_manager_app.User')),
            ],
        ),
    ]
